import os
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog, messagebox
from tkinter.ttk import Progressbar

from PyPDF2 import PdfMerger
import tk


global selected_files
selected_files = ""

def center_window():
    # Get the screen dimensions
    screen_width = window.winfo_screenwidth()
    screen_height = window.winfo_screenheight()

    # Calculate the x and y coordinates of the center of the screen
    x = (screen_width - window.winfo_width()) // 4
    y = (screen_height - window.winfo_height()) // 4

    # Move the window to the center of the screen
    window.geometry("+{}+{}".format(x, y))


def button1_clicked():
    global selected_files
    selected_files = filedialog.askopenfilenames(filetypes=[("PDF Files", "*.pdf")])
    if selected_files:
        messagebox.showinfo("Selected Files", f"{len(selected_files)} files selected.")


def button2_clicked():
    if not selected_files:
        messagebox.showinfo("No Files Selected", "Please select PDF files first.")
        return
    global output_file
    output_file = filedialog.asksaveasfilename(defaultextension=".pdf", filetypes=[("PDF Files", "*.pdf")])
    if not output_file:
        messagebox.showinfo("No Output File", "Please provide an output file name.")
        return

    if os.path.exists(output_file):
        result = messagebox.askyesno("Warning", "The output file already exists. Do you want to overwrite it?")
        window.title("Converting Please Wait!")
        if not result:
            return

    try:
        merger = PdfMerger()

        for file in selected_files:
            merger.append(file)

        merger.write(output_file)
        merger.close()

        messagebox.showinfo("Merge Successful", "PDF files Merged and saved successfully!")
        window.title("MERGE PDFs")
        button_3.config(cursor="hand2", state="normal")

    except Exception as e:
        messagebox.showerror("Merge Error", f"An error occurred during PDF conversion: {str(e)}")
        window.title("MERGE PDFs")
        button_3.config(cursor="hand2", state="normal")


def open_file():
    if not output_file:
        messagebox.showinfo("No File to Open", "Please convert PDF files first.")
        return

    try:
        os.startfile(output_file)
        window.destroy()

    except Exception as e:
        messagebox.showerror("File Open Error", f"An error occurred while opening the file: {str(e)}")
        window.destroy()


window = Tk()

window.geometry("773x458")
window.configure(bg="#FFFFFF")
window.title("MERGE PDFs")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=458,
    width=773,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=r'mergePdf\image_1.png')
image_1 = canvas.create_image(
    386.0,
    229.0,
    image=image_image_1
)

canvas.create_text(
    302.0,
    61.0,
    anchor="nw",
    text="Merge PDFs",
    fill="#000000",
    font=("Tienne Regular", 28 * -1)
)

button_image_1 = PhotoImage(
    file=r'mergePdf\button_1.png')
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button1_clicked,
    relief="flat"
)
button_1.place(
    x=127.0,
    y=158.0,
    width=229.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=r'mergePdf\button_2.png')
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=button2_clicked,
    relief="flat"
)
button_2.place(
    x=417.0,
    y=158.0,
    width=229.0,
    height=48.0
)

button_image_3 = PhotoImage(
    file=r'mergePdf\button_3.png')
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=open_file,
    relief="flat"
)
button_3.place(
    x=272.0,
    y=241.0,
    width=229.0,
    height=48.0
)
button_1.config(cursor="hand2")
button_2.config(cursor="hand2")
button_3.config(cursor="watch", state="disabled")
window.grab_set()
window.attributes('-topmost', True)
window.focus_force()
center_window()
window.resizable(False, False)
window.mainloop()
